---
title: "#TidyTuesday 2025 Week 17"
author: "R-Ladies Canberra, Sydney and Melbourne"
date: 05/06/2025
format: live-html
knitr: true
webr:
  packages:
    - tidyverse
---


{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

## Get the data 

This week's data is about the **useR! 2025 program**!

<https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-04-29>


### Option 1: Using the `tidytuesdayR` R package 

```{r}
#| eval: false
tuesdata <- tidytuesdayR::tt_load(2025, week = 17)
user2025 <- tuesdata$user2025
```

### Option 2: Read directly from GitHub


```{webr}
#| autorun: true
#| message: false
#| warning: false
library(tidyverse)
user2025 <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-29/user2025.csv')
```



## Explore the data 

```{webr}
glimpse(user2025)
```

How many talks per day?

```{webr}
user2025 |> 
  count(date)
```

Does the talk keywords contain AI or LLM?

```{webr}
user2025 |> 
  mutate(keywords_list = keywords |> 
           str_split(",") |> 
           map(str_trim)) |> 
  mutate(is_ai = map_lgl(keywords_list, ~str_detect(.x, "ai") | str_detect(.x, "llm"))) |> 
  count(is_ai)
```

## Final plot 

```{webr}

```


## Sharing your output

- Please submit your R code to reproduce your plot [**here**](https://www.dropbox.com/request/u9EY3wkus7sX8aqzoEir). We will put the code available [here](https://github.com/rladiessydney/Cross-chapter-TidyTuesday).
- Share your output and the code used to generate it on social media with the #TidyTuesday hashtag.
- Please note the following messages from [here](https://github.com/rfordatascience/tidytuesday/blob/main/sharing.md):

> We welcome all newcomers, enthusiasts, and experts to participate, but be mindful of these things:
>
> 1. The data set comes from the source article or the source that the article credits. Be mindful that the data is what it is! You are welcome to explore beyond the provided dataset, but the data is provided as a "toy" dataset to practice techniques on.  
> 2. This is NOT about criticizing the original article or graph. Real people made the graphs, collected or acquired the data! Focus on the provided dataset, learning, and improving your techniques in R.  
> 3. This is NOT about criticizing or tearing down your fellow data practitioners or their code! Be supportive and kind to each other! Like others' posts and help promote the data community!  
> 4. Use the hashtag #TidyTuesday on social media. You might also wish to add a language-specific hashtag: R: #RStats; Python: #PyData, #PydyTuesday; Julia: #JuliaLang, #TidierTuesday. On BlueSky, add the #DataBS (the BlueSky Data community) hashtag.
> 5. Include a picture of the visualization when you post to social media.  
> 6. Include alt text for any visualizations shared, so that everyone can participate! 
> 7. Include a copy of the code used to create your visualization when you post to social media.
8. Focus on improving your craft, even if you end up with something simple!  
9. Give credit to the original data source whenever possible.


